apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

nodeGroups:
    - name: ng-1
      instanceType: m5.large
      minSize: 1
      maxSize: 2
      iam:
        withAddonPolicies:
          albIngress: true
          autoScaler: true
          cloudWatch: true